name: Deploy Angular Project

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t azuresubha/angular:latest .
        docker push azuresubha/angular:latest

    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker stop angular-webserver || true
          docker rm angular-webserver || true
          docker container prune -f || true
          docker pull azuresubha/angular:latest
          docker run -d -p 80:80 --name angular-webserver azuresubha/angular:latest

